### PR TITLE
Docs and versions files updated

### PR DESCRIPTION
**Pull request by raiyankamal**
Preparing for release 0.5.0

@jankapunkt Please review and if possible also test in your local.

### CODE REVIEW

**Review by jankapunkt — APPROVED** [review]
Hi @raiyankamal the PR went totally off my radar, since I used the latest in my projects locally from this repo instead of atmosphere. Now on a new project I realized that publishing has waited for this PR.

Now here is everything okay, so I think you can publish 0.5

**Review by jankapunkt — APPROVED** [review]

**Comment by jankapunkt** [comment]
I found two hidden bugs after extending our app features and I added the fixes immediately. Could you please review and release the package?

**Comment by raiyankamal** [comment]
Thanks for checking and the fixes @jankapunkt 
I did a release: 0.5.0
Please check if everything looks fine now.

**Comment by jankapunkt** [comment]
Hi @raiyankamal could you please publish 0.5.0 to atmosphere? If there is anything that concerns you and prevents you from publishing please let me know.

**Comment by raiyankamal** [comment]
@jankapunkt I have published to atomsphere today. Plase check.

**Pull request merged**
