### PR TITLE
Autoform 7 compatibility

### PR DESCRIPTION
**Pull request by jankapunkt**
AutoForm 7 has been released and we need to bump this package in order to make it work with AF7 out of the box (I have tested and there is no different behavior).

Furthermore I bumped the noUiSlider npm version and fixed a minor bug.

 @raiyankamal would you mind reviewing and publishing?

### CODE REVIEW

**Comment by raiyankamal** [comment]
Hey there @jankapunkt 
Thanks for the PR. I was wondering if you would like to be the maintainer of this repo?

**Review by raiyankamal — APPROVED** [review]

**Comment by jankapunkt** [comment]
> Hey there @jankapunkt 
> Thanks for the PR. I was wondering if you would like to be the maintainer of this repo?

Sorry @raiyankamal for the delay, I would keep it updated since I will continue to use AutoForm 

I think Meteor allows to add people to groups,/Orgs for publishing packages.

**Comment by jankapunkt** [comment]
@raiyankamal can you please publish the package to atmosphere or add me on the Meteor cloud to the muqube group so I can publish?

**Comment by raiyankamal** [comment]
I published the latest code.

**Comment by raiyankamal** [comment]
We have an issue with the org on atmospherejs. The muqube account there is not an org, it's an individual account. This was an oversight on my part. I should've created an org instead. But now I cannot create a new org by the exact name. I can think of two options now:
1. Decide a new org name. That org will be created in both github and atmospherejs. You'll be a member in both orgs.
2. I can completely handover the ownership to you. Then the rest is your decision how you want to manage this package.



Let me know your opinion. Also, if you rather discuss this outside of github, you can reach me at raiyan [dot] kamal at gmail.

**Pull request merged**
